export const Data = [
  {name: 'Banker'},
  {name: 'Journalist'},
  {name: 'Swift Developer'},
  {name: 'Cleric'},
  {name: 'Financial Services Consultant'},
  {name: 'Beautician'},
  {name: 'Legal Practitional'},
  {name: 'Horologist'},
  {name: 'Caterer'},
  {name: 'Educationist'},
  {name: 'Administrator'},
  {name: 'Fasion Designer'},
  {name: 'Architect'},
  {name: 'Horticulturist'},
  {name: 'Business Trader'},
  {name: 'Farmer'},
  {name: 'Information Technologist'},
  {name: 'Zoologist'},
  {name: 'Defence'},
  {name: 'Agric Engineer'},
  {name: 'Cleric'},
  {name: 'Engineer'},
  {name: 'Food Scientist'},
  {name: 'Accountant'},
  {name: 'Civil Servant'},
  {name: 'Software Developer'},
  {name: 'Economist'},
  {name: 'Importer and Exporter'},
  {name: 'Biostem Engineer'},
  {name: 'Native Developer'},
  {name: 'Communication Technologist'},
  {name: 'Java Developer'},
];
